### ISSUE TITLE
TP4056 misalignment of the through holes

### ISSUE THREAD

**Issue by blizzard25** [wasab1i/SlimeVr-PCB-BMI160#1]
The through holes labelled B- and B+ on the TP4056 are misaligned with the hardware. They are about 2mm to wide on both sides, they need to be closer to the center of the board. Everything else was aligned great when I had these printed, but unfortunately I wasn't able to get the TP4056 on.

**Comment by wasab1i** [comment]
bummer. Try using some jumper wire instead of soldering directly the tp4056

**Comment by StrideVRM** [comment]
That's what I ended up doing, just making a note if you want to fix the design. But everything else is great
